#!/bin/sh -eu

xdg_config_home=${XDG_CONFIG_HOME:-$HOME/.config}
keyfile="$xdg_config_home/nvchecker/keyfile.toml"

nvchecker_output_file=$(mktemp)
nvchecker -k "$keyfile" -c watchlist.nvchecker.toml --logger json \
  > "$nvchecker_output_file"

exit_code=0

while IFS= read -r line; do
  name=$(echo "$line" | jq -r '.name')
  upstream_version=$(echo "$line" | jq -r '.version')
  current_version=$(jq -r --arg name "$name" '.[$name]' watchlist.current-versions.json)
  if [ "$current_version" != "$upstream_version" ]; then
    echo "$name $upstream_version"
    exit_code=1
  fi
done < "$nvchecker_output_file"

exit $exit_code
