[__config__]
oldver = "watchlist.current-versions.json"
newver = "~/.local/state/watchlist.new-versions.json"

[dotnet-sdk]
source = "archpkg"
archpkg = "dotnet-sdk"

[ruby-base64]
source = "archpkg"
archpkg = "ruby-base64"

[python-flask]
source = "archpkg"
archpkg = "python-flask"
