[dotnet-sdk]
source = "archpkg"
archpkg = "dotnet-sdk"

[python-pint]
source = "archpkg"
archpkg = "python-pint"

[ruby-base64]
source = "archpkg"
archpkg = "ruby-base64"

[ruby-maxitest]
source = "archpkg"
archpkg = "ruby-maxitest"
